### ISSUE TITLE
ActiveJob::Plugins::Resque::Solo::Inspector.resque_present? not working

### ISSUE THREAD

**Issue by mike-burns** [kinkade/active_job_resque_solo#3]
```
irb(main)> ActiveJob::Base.queue_adapter
=> #<ActiveJob::QueueAdapters::ResqueAdapter:0x00001a97a023e810>
irb(main)> ActiveJob::Base.queue_adapter == ActiveJob::QueueAdapters::ResqueAdapter
=> false
irb(main)> ActiveJob::Base.queue_adapter === ActiveJob::QueueAdapters::ResqueAdapter
=> false
irb(main)> ActiveJob::Base.queue_adapter.is_a? ActiveJob::QueueAdapters::ResqueAdapter
=> true
```

This gem didn't just work for me (it enqueued duplicates) and I traced it back to this. When I re-opened the method to use `#is_a?` instead of `#==`, it worked (no duplicates).

**Comment by kinkade** [comment]
Thank you, @mike-burns, that's a very good suggestion to use `#is_a?` instead of `#==`.  I'll write up a PR with tests to reproduce the issue and merge it in soon.  Let me know if you would like attribution in the readme.

**Comment by mike-burns** [comment]
No attribution needed. Thank you for looking at this!

**Comment by kinkade** [comment]
Fixed in this commit (https://github.com/kinkade/active_job_resque_solo/commit/e01f572adafd8a78454e1359a8fb3dc901cdf952)
